name: build-in-action

on: [push]

jobs:
  try-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
          hostnamectl
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          git config user.name "Munish Mehta"
          git config credential.username mumehta
          git config user.email munish.mehta.au@gmail.com
          git config core.sshCommand "ssh -i ~/.ssh/id_ed25519"
          # git clone git@github.com:$GITHUB_REPOSITORY
          git config --list
